### PR TITLE
Test

### PR DESCRIPTION
**Pull request by jonathanfunk**
Just testing

### CODE REVIEW

**Comment by jonathanfunk** [comment]
Added view port meta tag. This will allow the site to scale properly on mobile.

**Comment by jonathanfunk** [comment]
Changed height of the main body to 90vh and footer to 10vh so the whole screen is filled.

**Comment by jonathanfunk** [comment]
Only font used in this project was Open Sans Light. Deleted everything else.

**Comment by jonathanfunk** [comment]
Caption text had a blue underline so I got rid of them.

**Comment by rcass** [comment]
Good changes!

**Pull request merged**
